import Head from 'next/head'
import Grid from 'components/Grid'
import Navbar from 'components/Navbar'

import Image from 'next/image'

import banner from '../public/img/contacto.jpg'

import {useAppWidth} from 'context'

export default function Home() {
	const [width] = useAppWidth()
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex flex-wrap my-3 mr-3 md:my-4 md:mr-4">
				<Navbar />
				<div className="relative h-full w-full md:w-[85%] lg:w-[87%] xl:w-[89%]">
					<Grid hidden />
					<div className="flex flex-wrap">
						{/* imgs */}
						<h1
							className="font-sec text-3xl leading-tight"
							style={{
								width: `${width * 24}px`,
								height: `${width * 1}px`,
								marginLeft: `${width * 2}px`,
								marginTop: `${width * 0.7}px`,
							}}
						>
							Conversemos.
						</h1>
						<div
							className="overflow-hidden"
							style={{
								width: `${width * 10}px`,
								height: `${width * 14}px`,
								marginLeft: `${width * 2}px`,
								marginTop: `${width * 0.7}px`,
							}}
						>
							<Image
								src={banner}
								alt="Somos Visualiza"
								placeholder="blur"
								className="object-cover"
							/>
						</div>
						<div
							style={{
								width: `${width * 11}px`,
								height: `${width * 12}px`,
								marginLeft: width,
								marginTop: `${width * 4}px`,
							}}
							className="pl-3"
						>
							<p className="text-sm font-sec leading-none">Email</p>
							<a className="text-sm" href="mailto:contacto@visualiza.pe">
								contacto@visualiza.pe
							</a>

							<p className="text-sm font-sec leading-none mt-6">Número</p>
							<a className="text-sm" href="tel:+51956453424">
								+51 956 453 424
							</a>

							<p className="text-sm leading-snug mt-8">
								Avenida dos de mayo 1830 <br />
								San Isidro 17056 <br />
								Lima - Perú
							</p>
						</div>
					</div>

					{/* <Footer /> */}
				</div>
			</main>
		</>
	)
}
