import Head from 'next/head'
import Image from 'next/image'
import Grid from '../src/components/Grid'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="pt-16 h-full overflow-hidden">
        <div className="relative h-full">
            <Grid />
            <div className="flex flex-wrap px-4 md:px-0">
                <div
                    className="w-full mt-4
                md:md-grid-img lg:lg-grid-img xl:xl-grid-img
                md:md-grid-ml-1 lg:lg-grid-ml-1 xl:xl-grid-ml-1
                md:md-grid-mt-1 lg:lg-grid-mt-1 xl:xl-grid-mt-1
                "
                >
                    <div className="relative w-full h-0 overflow-hidden ar4x5 md:ar4x6">
                        <a href="#">
                            <img
                                src="https://images.unsplash.com/photo-1619937812459-bf054619c8f8?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80"
                                className="w-full h-full absolute top-0 left-0 object-cover"
                                alt=""
                            />
                        </a>
                    </div>
                </div>

                <div
                    className="w-full mt-4
                md:md-grid-img lg:lg-grid-img xl:xl-grid-img
                md:md-grid-ml-1 lg:lg-grid-ml-1 xl:xl-grid-ml-1
                md:md-grid-mt-2 lg:lg-grid-mt-2 xl:xl-grid-mt-2
                "
                >
                    <div className="relative w-full h-0 overflow-hidden ar4x5 md:ar3x3">
                        <a href="#">
                            <img
                                src="https://images.unsplash.com/photo-1619918577835-7f407ea12a2c?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80"
                                className="w-full h-full absolute top-0 left-0 object-cover"
                                alt=""
                            />
                        </a>
                    </div>
                </div>

                <div
                    className="w-full mt-4
                md:md-grid-img lg:lg-grid-img xl:xl-grid-img
                md:md-grid-ml-1 lg:lg-grid-ml-1 xl:xl-grid-ml-1
                md:md-grid-mt-1 lg:lg-grid-mt-3 xl:xl-grid-mt-3
                "
                >
                    <div className="relative w-full h-0 overflow-hidden ar4x6">
                        <a href="#">
                            <img
                                src="https://images.unsplash.com/photo-1619918577835-7f407ea12a2c?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80"
                                className="w-full h-full absolute top-0 left-0 object-cover"
                                alt=""
                            />
                        </a>
                    </div>
                </div>

                <div
                    className="w-full mt-4
                md:md-grid-img lg:lg-grid-img xl:xl-grid-img
                md:md-grid-ml-1 lg:lg-grid-ml-1 xl:xl-grid-ml-1
                md:md-grid-mt-n1 lg:lg-grid-mt-n1 xl:xl-grid-mt-2
                "
                >
                    <div className="relative w-full h-0 overflow-hidden ar4x6">
                        <a href="#">
                            <img
                                src="https://images.unsplash.com/photo-1619937812459-bf054619c8f8?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80"
                                className="w-full h-full absolute top-0 left-0 object-cover"
                                alt=""
                            />
                        </a>
                    </div>
                </div>

                <div
                    className="w-full mt-4
                    md:md-grid-img lg:lg-grid-img xl:xl-grid-img
                    md:md-grid-ml-1 lg:lg-grid-ml-1 xl:xl-grid-ml-1
                    md:md-grid-mt-1 lg:lg-grid-mt-n3 xl:xl-grid-mt-n1
                    "
                >
                    <div className="relative w-full h-0 overflow-hidden ar3x3">
                        <a href="#">
                            <img
                                src="https://images.unsplash.com/photo-1619918577835-7f407ea12a2c?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80"
                                className="w-full h-full absolute top-0 left-0 object-cover"
                                alt=""
                            />
                        </a>
                    </div>
                </div>

                <div
                    className="w-full mt-4
                md:md-grid-img lg:lg-grid-img xl:xl-grid-img
                md:md-grid-ml-1 lg:lg-grid-ml-1 xl:xl-grid-ml-1
                md:md-grid-mt-n1 lg:lg-grid-mt-1 xl:xl-grid-mt-n3
                "
                >
                    <div className="relative w-full h-0 overflow-hidden ar4x6">
                        <a href="#">
                            <img
                                src="https://images.unsplash.com/photo-1619937812459-bf054619c8f8?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80"
                                className="w-full h-full absolute top-0 left-0 object-cover"
                                alt=""
                            />
                        </a>
                    </div>
                </div>

                <div
                    className="w-full mt-3
                md:md-grid-img lg:lg-grid-img xl:xl-grid-img
                md:md-grid-ml-1 lg:lg-grid-ml-1 xl:xl-grid-ml-1
                md:md-grid-mt-1 lg:lg-grid-mt-n1 xl:xl-grid-mt-1
                "
                >
                    <div className="relative w-full h-0 overflow-hidden ar3x3">
                        <a href="#">
                            <img
                                src="https://images.unsplash.com/photo-1619918577835-7f407ea12a2c?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80"
                                className="w-full h-full absolute top-0 left-0 object-cover"
                                alt=""
                            />
                        </a>
                    </div>
                </div>

                <div className="grid-img grid-ml-1 grid-mt-0">
                    <div className="relative w-full h-0 overflow-hidden ar3x3">
                        <a href="#">
                            <img
                                src="https://images.unsplash.com/photo-1619918577835-7f407ea12a2c?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80"
                                className="w-full h-full absolute top-0 left-0 object-cover"
                                alt=""
                            />
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
