import Head from 'next/head'
import Grid from 'components/Grid'
import Navbar from 'components/Navbar'

import Image from 'next/image'
import Footer from 'components/Footer'

import banner from '../public/img/oficina.jpg'

import {useAppWidth} from 'context'
import Logo from 'components/svgs/Logo'
import logos from 'data/logos'
export default function Home() {
	const [width] = useAppWidth()
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex flex-wrap my-3 mr-3 md:my-4 md:mr-4">
				<Navbar />
				<div className="relative h-full w-full md:w-[85%] lg:w-[87%] xl:w-[89%]">
					<Grid />
					<div className="flex flex-wrap">
						{/* imgs */}
						<div
							className="overflow-hidden"
							style={{
								width: `${width * 11}px`,
								height: `${width * 16}px`,
								marginLeft: `${width * 3}px`,
								marginTop: width,
							}}
						>
							<Image src={banner} alt="Somos Visualiza" placeholder="blur" />
						</div>
						<div
							style={{
								width: `${width * 11}px`,
								height: `${width * 12}px`,
								marginLeft: width,
								marginTop: `${width * 4}px`,
							}}
							className="pl-3"
						>
							<h1 className="font-sec text-[40px] leading-tight">
								Somos{' '}
								<Logo
									color="black"
									classname="w-[106px] md:w-[96px] lg:w-[106px] 2xl:w-[216px]"
								/>
							</h1>
							<p style={{marginTop: `${width * 3}px`}} classname="">
								Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim
								officiis obcaecati dolor deleniti itaque numquam maiores
								voluptatibus consequatur eius necessitatibus pariatur molestiae
								explicabo possimus, cumque odit laboriosam! Asperiores cum
								cupiditate dolore laboriosam obcaecati alias dolor repellat.
								Quae ipsum, ipsam repudiandae repellendus iure corrupti eligendi
								reiciendis neque quis eum voluptatem quibusdam? Sunt facilis
								deleniti iusto voluptate quia maiores ratione voluptas
								accusantium.
							</p>
						</div>
						<div
							style={{
								width: `${width * 24}px`,
								height: `${width * 10}px`,
								marginLeft: `${width * 3}px`,
								marginTop: width,
							}}
						>
							<h3 className="font-sec text-lg pt-5 pl-1">Nuestros clientes.</h3>
							<div
								className="flex flex-wrap"
								style={{marginTop: width, columnGap: width}}
							>
								{logos.map(({logo, alt}) => (
									<div
										style={{
											width: `${width * 3}px`,
											height: `${width * 2}px`,
											marginBottom: width,
										}}
									>
										<Image src={logo} alt={alt} placeholder="blur" />
									</div>
								))}
							</div>
						</div>
					</div>

					{/* <Footer /> */}
				</div>
			</main>
		</>
	)
}
