import Head from 'next/head'
import Grid from 'components/Grid'
import Navbar from 'components/Navbar'

import Image from 'next/image'
import Footer from 'components/Footer'

import banner from '../public/img/oficina.jpg'

import {useAppWidth} from 'context'
import Logo from 'components/svgs/Logo'
import logos from 'data/logos'
export default function Home() {
	const [width] = useAppWidth()
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex flex-wrap my-3 mx-3 md:my-4 md:ml-0 md:mr-4">
				<Navbar />
				<div className="relative h-full w-full md:w-[85%] lg:w-[87%] xl:w-[89%]">
					<Grid />
					<div className="flex flex-wrap">
						{/* imgs */}
						<div
							className="overflow-hidden"
							style={{
								width: `${width * 11}px`,
								height: `${width * 16}px`,
								marginLeft: `${width * 3}px`,
								marginTop: width,
							}}
						>
							<Image src={banner} alt="Somos Visualiza" placeholder="blur" />
						</div>
						<div
							style={{
								width: `${width * 11}px`,
								height: `${width * 12}px`,
								marginLeft: width,
								marginTop: `${width * 4}px`,
							}}
							className="pl-3"
						>
							<h1
								style={{height: width}}
								className="flex flex-col justify-center font-sec text-5xl"
							>
								Somos
							</h1>
							<h2 style={{height: width}}>
								<Logo
									color="black"
									classname="w-[106px] md:w-[96px] lg:w-[106px] 2xl:w-[216px]"
								/>
							</h2>
							<p
								style={{
									marginTop: `${width * 3}px`,
									lineHeight: 1.14,
									fontSize: 17,
								}}
								className="pt-4"
							>
								Somos un equipo multidisciplinario de arquitectos, diseñadores y
								artistas.
								<br />
								Todos enamorados del arte digital y la visualización en tres
								dimensiones.
								<br />
								Disfrutamos que los proyectos sean un reto, que nos exijan
								aprender constantemente. Queremos que nos busquen por un
								resultado único, una metodología innovadora, y el aporte
								creativo en todo el proceso. Creemos en la oportunidad de
								plasmar espacios aun no existentes y contar una historia en
								ellos.
								<br />
								Compromiso, comunicación y pasión son partes fundamentales de
								cada proyecto. Amamos lo que hacemos. <br />
								Es así de simple.
							</p>
						</div>
						<div
							style={{
								width: `${width * 24}px`,
								height: `${width * 10}px`,
								marginLeft: `${width * 3}px`,
								marginTop: width,
							}}
						>
							<h3
								className="font-sec text-xl pl-1"
								style={{height: width, paddingTop: width / 2}}
							>
								Nuestros clientes.
							</h3>
							<div
								className="flex flex-wrap"
								style={{marginTop: width, columnGap: width}}
							>
								{logos.map(({logo, alt}) => (
									<div
										style={{
											width: `${width * 3}px`,
											height: `${width * 2}px`,
											marginBottom: width,
										}}
									>
										<Image src={logo} alt={alt} placeholder="blur" />
									</div>
								))}
							</div>
						</div>
					</div>

					{/* <Footer /> */}
				</div>
			</main>
		</>
	)
}
