import Head from 'next/head'
import {useRouter} from 'next/router'
import {AnimateSharedLayout, AnimatePresence, motion} from 'framer-motion'

import Grid from 'components/Grid'
import Navbar from 'components/Navbar'
import ListPortfolio from 'components/List/ListPortfolio'
import Item from 'components/List/Item'
import useLoaded from 'hooks/useLoaded'
import ButtonWsp from 'components/ButtonWsp'

export default function Home() {
	const {
		query: {projectId},
	} = useRouter()
	const loaded = useLoaded()
	return (
		<AnimateSharedLayout type="crossfade">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<motion.main
				initial={{opacity: 0}}
				animate={{opacity: loaded ? 1 : 0}}
				transition={{duration: 0.8}}
				className="flex flex-wrap my-3 mx-3 md:my-4 md:ml-0 md:mr-4"
			>
				<Navbar />
				<div className="relative h-full w-full md:w-[85%] lg:w-[87%] xl:w-[89%]">
					<Grid loaded={loaded} />
					<div className="flex flex-wrap">
						<ListPortfolio />
						<AnimatePresence>
							{projectId && <Item id={projectId} key="item" />}
						</AnimatePresence>
					</div>
				</div>
				<ButtonWsp />
			</motion.main>
		</AnimateSharedLayout>
	)
}
