import React from 'react'
import Head from 'next/head'
import Grid from 'components/Grid'
import Navbar from 'components/Navbar'

import Image from 'next/image'
import Footer from 'components/Footer'

import banner from '../public/img/servicios.jpg'
import modelado3D from '../public/img/servicios/MODELADO_3D.webp'
import drone from '../public/img/servicios/VISTAS_AEREAS_DRONE.webp'
import visual from '../public/img/servicios/VISUALIZACION_ARQUITECTONICA.webp'

import {useAppQuery, useAppWidth} from 'context'

import useMedia from 'hooks/useMedia'
import videojs from 'video.js'
import 'videojs-youtube'
import 'video.js/dist/video-js.css'

export default function Home() {
	const [width] = useAppWidth()
	const query = useAppQuery()
	const isMobileTablet = useMedia('(max-width: 1047px)')

	const size = React.useMemo(() => {
		if (query === 'xl') {
			return {imgWidth: 23, imgHeight: 13, imgMl: 3}
		} else if (query === 'lg') {
			return {imgWidth: 18, imgHeight: 10, imgMl: 2}
		} else if (query === 'md') {
			return {imgWidth: 13, imgHeight: 7, imgMl: 1}
		} else {
			return {imgWidth: 6, imgHeight: 4, imgMl: 1}
		}
	}, [query])

	React.useEffect(() => {
		const player = videojs('vs-video', {
			fluid: true,
			playbackRates: [0.5, 1, 1.5, 2],
			playsinline: true,
			aspectRatio: '16:9',
		})
		const player2 = videojs('vs-video2', {
			fluid: true,
			playbackRates: [0.5, 1, 1.5, 2],
			playsinline: true,
			aspectRatio: '16:9',
		})
		return () => {
			if (player && player2) {
				player && player.dispose()
				player2 && player2.dispose()
			}
		}
	}, [])

	return (
		<>
			<Head>
				<title>Create Nesxt App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex flex-wrap my-3 mx-3 md:my-4 md:ml-0 md:mr-4">
				<Navbar />
				<div className="relative h-full w-full md:w-[85%] lg:w-[87%] xl:w-[89%]">
					<Grid />
					<div className="flex flex-wrap">
						{/* imgs */}
						<h2
							style={{
								height: width,
								marginLeft: `${width * size.imgMl}px`,
								marginTop: width,
							}}
							className="font-sec text-[22px] md:text-[28px] w-full flex items-center pl-1 pt-2"
						>
							Modelado 3D.
						</h2>
						<div
							className="overflow-hidden custom-height"
							style={{
								width: `${width * size.imgWidth}px`,
								height: `${width * size.imgHeight}px`,
								marginLeft: `${width * size.imgMl}px`,
								zIndex: 1,
							}}
						>
							<Image
								src={modelado3D}
								alt="Modelado 3D"
								placeholder="blur"
								className="object-cover"
							/>
						</div>

						<h2
							style={{
								height: width,
								marginLeft: `${width * size.imgMl}px`,
								marginTop: width,
							}}
							className="font-sec text-[22px] md:text-[28px] w-full flex items-center pl-1 pt-2"
						>
							Tour virtual 360.
						</h2>
						<div
							className="overflow-hidden custom-height"
							style={{
								width: `${width * size.imgWidth}px`,
								height: `${width * size.imgHeight}px`,
								marginLeft: `${width * size.imgMl}px`,
								zIndex: 1,
							}}
						>
							<iframe
								className="ku-embed"
								frameborder="0"
								allowFullScreen
								allow="xr-spatial-tracking; gyroscope; accelerometer"
								scrolling="no"
								style={{width: '100%', height: '100%'}}
								src="https://mls.kuu.la/share/collection/7kHxv?fs=1&vr=1&autorotate=0.22&autop=25&thumbs=1&inst=0"
							></iframe>
						</div>

						<h2
							style={{
								height: width,
								marginLeft: `${width * size.imgMl}px`,
								marginTop: width,
							}}
							className="font-sec text-[22px] md:text-[28px] w-full flex items-center pl-1 pt-2"
						>
							Visualización arquitectónica.
						</h2>
						<div
							className="overflow-hidden custom-height"
							style={{
								width: `${width * size.imgWidth}px`,
								height: `${width * size.imgHeight}px`,
								marginLeft: `${width * size.imgMl}px`,
								zIndex: 1,
							}}
						>
							<Image
								src={visual}
								alt="Visualización arquitectónica"
								placeholder="blur"
								className="object-cover"
							/>
						</div>

						<h2
							style={{
								height: width,
								marginLeft: `${width * size.imgMl}px`,
								marginTop: width,
							}}
							className="font-sec text-[22px] md:text-[28px] w-full flex items-center pl-1 pt-2"
						>
							Vistas aéreas - drone.
						</h2>
						<div
							className="overflow-hidden custom-height"
							style={{
								width: `${width * size.imgWidth}px`,
								height: `${width * size.imgHeight}px`,
								marginLeft: `${width * size.imgMl}px`,
								zIndex: 1,
							}}
						>
							<Image
								src={drone}
								alt="Vistas aéreas - drone"
								className="object-cover"
								placeholder="blur"
							/>
						</div>

						<h2
							style={{
								height: width,
								marginLeft: `${width * size.imgMl}px`,
								marginTop: width,
							}}
							className="font-sec text-[22px] md:text-[28px] w-full flex items-center pl-1 pt-2"
						>
							Recorridos virtuales.
						</h2>
						<div
							className="overflow-hidden custom-height"
							style={{
								width: `${width * size.imgWidth}px`,
								height: `${width * size.imgHeight}px`,
								marginLeft: `${width * size.imgMl}px`,
								zIndex: 1,
							}}
						>
							<video
								controls
								id="vs-video2"
								className="video-js vjs-big-play-centered"
								width="750"
								height="500"
								// poster={allData?.productData?.acf?.video?.thumbnail?.url}
								data-setup='{ "techOrder": ["youtube"], "sources": [{ "type": "video/youtube", "src": "https://www.youtube.com/embed/LthDz0yyUsE"}], "youtube": { "iv_load_policy": 1 } }'
							/>
						</div>

						<h2
							style={{
								height: width,
								marginLeft: `${width * size.imgMl}px`,
								marginTop: width,
							}}
							className="font-sec text-[22px] md:text-[28px] w-full flex items-center pl-1 pt-2"
						>
							Marketing inmobiliario.
						</h2>
						<div
							className="overflow-hidden custom-height"
							style={{
								width: `${width * size.imgWidth}px`,
								height: `${width * size.imgHeight}px`,
								marginLeft: `${width * size.imgMl}px`,
								zIndex: 1,
								marginBottom: `${width * (isMobileTablet ? 1 : 2)}px`,
							}}
						>
							<video
								controls
								id="vs-video"
								className="video-js vjs-big-play-centered"
								width="750"
								height="500"
								// poster={allData?.productData?.acf?.video?.thumbnail?.url}
								data-setup='{ "techOrder": ["youtube"], "sources": [{ "type": "video/youtube", "src": "https://www.youtube.com/embed/0uekokAx7hM"}], "youtube": { "iv_load_policy": 1 } }'
							/>
						</div>
					</div>

					{/* <Footer /> */}
				</div>
			</main>
		</>
	)
}
