import React from 'react'
import Head from 'next/head'
import Grid from 'components/Grid'
import Navbar from 'components/Navbar'

import Image from 'next/image'
import Footer from 'components/Footer'

import banner from '../public/img/servicios.jpg'

import {useAppQuery, useAppWidth} from 'context'

import useMedia from 'hooks/useMedia'
export default function Home() {
	const [width] = useAppWidth()
	const query = useAppQuery()
	const isMobileTablet = useMedia('(max-width: 1047px)')

	const size = React.useMemo(() => {
		if (query === 'xl') {
			return {imgWidth: 23, imgHeight: 13, imgMl: 3}
		} else if (query === 'lg') {
			return {imgWidth: 18, imgHeight: 10, imgMl: 2}
		} else if (query === 'md') {
			return {imgWidth: 13, imgHeight: 7, imgMl: 1}
		} else {
			return {imgWidth: 6, imgHeight: 4, imgMl: 1}
		}
	}, [query])
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex flex-wrap my-3 mx-3 md:my-4 md:ml-0 md:mr-4">
				<Navbar />
				<div className="relative h-full w-full md:w-[85%] lg:w-[87%] xl:w-[89%]">
					<Grid />
					<div className="flex flex-wrap">
						{/* imgs */}
						<h2
							style={{
								height: width,
								marginLeft: `${width * size.imgMl}px`,
								marginTop: width,
							}}
							className="font-sec text-[28px] w-full flex items-center pl-1 pt-2"
						>
							Modelado 3D.
						</h2>
						<div
							className="overflow-hidden custom-height"
							style={{
								width: `${width * size.imgWidth}px`,
								height: `${width * size.imgHeight}px`,
								marginLeft: `${width * size.imgMl}px`,
							}}
						>
							<Image src={banner} alt="Somos Visualiza" placeholder="blur" />
						</div>

						<h2
							style={{
								height: width,
								marginLeft: `${width * size.imgMl}px`,
								marginTop: width,
							}}
							className="font-sec text-[28px] w-full flex items-center pl-1 pt-2"
						>
							Tour virtual 360.
						</h2>
						<div
							className="overflow-hidden custom-height"
							style={{
								width: `${width * size.imgWidth}px`,
								height: `${width * size.imgHeight}px`,
								marginLeft: `${width * size.imgMl}px`,
							}}
						>
							<Image src={banner} alt="Somos Visualiza" placeholder="blur" />
						</div>

						<h2
							style={{
								height: width,
								marginLeft: `${width * size.imgMl}px`,
								marginTop: width,
							}}
							className="font-sec text-[28px] w-full flex items-center pl-1 pt-2"
						>
							Visualización arquitectónica.
						</h2>
						<div
							className="overflow-hidden custom-height"
							style={{
								width: `${width * size.imgWidth}px`,
								height: `${width * size.imgHeight}px`,
								marginLeft: `${width * size.imgMl}px`,
							}}
						>
							<Image src={banner} alt="Somos Visualiza" placeholder="blur" />
						</div>

						<h2
							style={{
								height: width,
								marginLeft: `${width * size.imgMl}px`,
								marginTop: width,
							}}
							className="font-sec text-[28px] w-full flex items-center pl-1 pt-2"
						>
							Fotografía aérea.
						</h2>
						<div
							className="overflow-hidden custom-height"
							style={{
								width: `${width * size.imgWidth}px`,
								height: `${width * size.imgHeight}px`,
								marginLeft: `${width * size.imgMl}px`,
							}}
						>
							<Image src={banner} alt="Somos Visualiza" placeholder="blur" />
						</div>

						<h2
							style={{
								height: width,
								marginLeft: `${width * size.imgMl}px`,
								marginTop: width,
							}}
							className="font-sec text-[28px] w-full flex items-center pl-1 pt-2"
						>
							Recorridos virtuales.
						</h2>
						<div
							className="overflow-hidden custom-height"
							style={{
								width: `${width * size.imgWidth}px`,
								height: `${width * size.imgHeight}px`,
								marginLeft: `${width * size.imgMl}px`,
							}}
						>
							<Image src={banner} alt="Somos Visualiza" placeholder="blur" />
						</div>

						<h2
							style={{
								height: width,
								marginLeft: `${width * size.imgMl}px`,
								marginTop: width,
							}}
							className="font-sec text-[28px] w-full flex items-center pl-1 pt-2"
						>
							Marketing inmobiliario.
						</h2>
						<div
							className="overflow-hidden custom-height"
							style={{
								width: `${width * size.imgWidth}px`,
								height: `${width * size.imgHeight}px`,
								marginLeft: `${width * size.imgMl}px`,
								marginBottom: `${width * (isMobileTablet ? 1 : 2)}px`,
							}}
						>
							<Image src={banner} alt="Somos Visualiza" placeholder="blur" />
						</div>
					</div>

					{/* <Footer /> */}
				</div>
			</main>
		</>
	)
}
