import Head from 'next/head'
import Grid from 'components/Grid'
import Navbar from 'components/Navbar'

import Image from 'next/image'
import Footer from 'components/Footer'

import banner from '../public/img/servicios.jpg'

import {useAppWidth} from 'context'
import Logo from 'components/svgs/Logo'
import logos from 'data/logos'
export default function Home() {
	const [width] = useAppWidth()
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex flex-wrap my-3 mx-3 md:my-4 md:ml-0 md:mr-4">
				<Navbar />
				<div className="relative h-full w-full md:w-[85%] lg:w-[87%] xl:w-[89%]">
					<Grid />
					<div className="flex flex-wrap">
						{/* imgs */}
						<h2
							style={{
								height: width,
								marginLeft: `${width * 3}px`,
								marginTop: width,
							}}
							className="font-sec text-[28px] w-full flex items-center pl-1 pt-2"
						>
							Modelado 3D.
						</h2>
						<div
							className="overflow-hidden"
							style={{
								width: `${width * 23}px`,
								height: `${width * 13}px`,
								marginLeft: `${width * 3}px`,
							}}
						>
							<Image src={banner} alt="Somos Visualiza" placeholder="blur" />
						</div>

						<h2
							style={{
								height: width,
								marginLeft: `${width * 3}px`,
								marginTop: width,
							}}
							className="font-sec text-[28px] w-full flex items-center pl-1 pt-2"
						>
							Tour virtual 360.
						</h2>
						<div
							className="overflow-hidden"
							style={{
								width: `${width * 23}px`,
								height: `${width * 13}px`,
								marginLeft: `${width * 3}px`,
							}}
						>
							<Image src={banner} alt="Somos Visualiza" placeholder="blur" />
						</div>

						<h2
							style={{
								height: width,
								marginLeft: `${width * 3}px`,
								marginTop: width,
							}}
							className="font-sec text-[28px] w-full flex items-center pl-1 pt-2"
						>
							Visualización arquitectónica.
						</h2>
						<div
							className="overflow-hidden"
							style={{
								width: `${width * 23}px`,
								height: `${width * 13}px`,
								marginLeft: `${width * 3}px`,
							}}
						>
							<Image src={banner} alt="Somos Visualiza" placeholder="blur" />
						</div>

						<h2
							style={{
								height: width,
								marginLeft: `${width * 3}px`,
								marginTop: width,
							}}
							className="font-sec text-[28px] w-full flex items-center pl-1 pt-2"
						>
							Fotografía aérea.
						</h2>
						<div
							className="overflow-hidden"
							style={{
								width: `${width * 23}px`,
								height: `${width * 13}px`,
								marginLeft: `${width * 3}px`,
							}}
						>
							<Image src={banner} alt="Somos Visualiza" placeholder="blur" />
						</div>

						<h2
							style={{
								height: width,
								marginLeft: `${width * 3}px`,
								marginTop: width,
							}}
							className="font-sec text-[28px] w-full flex items-center pl-1 pt-2"
						>
							Recorridos virtuales.
						</h2>
						<div
							className="overflow-hidden"
							style={{
								width: `${width * 23}px`,
								height: `${width * 13}px`,
								marginLeft: `${width * 3}px`,
							}}
						>
							<Image src={banner} alt="Somos Visualiza" placeholder="blur" />
						</div>

						<h2
							style={{
								height: width,
								marginLeft: `${width * 3}px`,
								marginTop: width,
							}}
							className="font-sec text-[28px] w-full flex items-center pl-1 pt-2"
						>
							Marketing inmobiliario.
						</h2>
						<div
							className="overflow-hidden"
							style={{
								width: `${width * 23}px`,
								height: `${width * 13}px`,
								marginLeft: `${width * 3}px`,
								marginBottom: `${width * 2}px`,
							}}
						>
							<Image src={banner} alt="Somos Visualiza" placeholder="blur" />
						</div>
					</div>

					{/* <Footer /> */}
				</div>
			</main>
		</>
	)
}
